return {
  'nvim-neotest/neotest',
  lazy = true,
  dependencies = {
    'nvim-neotest/nvim-nio',
    'nvim-lua/plenary.nvim',
    'antoinemadec/FixCursorHold.nvim',
    'nvim-treesitter/nvim-treesitter',
    'nvim-neotest/neotest-python',
    'fredrikaverpil/neotest-golang',
    'nvim-neotest/neotest-jest',
    'marilari88/neotest-vitest',
    'benelan/neotest-stenciljs',
    'thenbe/neotest-playwright',
    'olimorris/neotest-rspec',
    'zidhuss/neotest-minitest',
    'sidlatau/neotest-dart',
    'shunsambongi/neotest-testthat',
    'olimorris/neotest-phpunit',
    'V13Axel/neotest-pest',
    'mrcjkb/rustaceanvim',
    'jfpedroza/neotest-elixir',
    'Issafalcon/neotest-dotnet',
    'stevanmilic/neotest-scala',
    'mrcjkb/neotest-haskell',
    'MarkEmmons/neotest-deno',
    'rcasia/neotest-java',
    'codymikol/neotest-kotlin.nvim',
    'llllvvuu/neotest-foundry',
    'lawrence-laz/neotest-zig',
    'alfaix/neotest-gtest',
    'weilbith/neotest-gradle',
    'sluongng/neotest-bazel',
    'rcasia/neotest-bash',
    'TheSnakeWitcher/hardhat.nvim',
    'mmllr/neotest-swift-testing',
  },
  opts = {
    adapters = {
      ['neotest-python'] = {},
      ['neotest-golang'] = {},
      ['neotest-jest'] = {},
      ['neotest-vitest'] = {},
      ['neotest-stenciljs'] = {},
      ['neotest-playwright'] = {},
      ['neotest-rspec'] = {},
      ['neotest-minitest'] = {},
      ['neotest-dart'] = {},
      ['neotest-testthat'] = {},
      ['neotest-phpunit'] = {},
      ['neotest-pest'] = {},
      ['rustaceanvim'] = {},
      ['neotest-elixir'] = {},
      ['neotest-dotnet'] = {},
      ['neotest-scala'] = {},
      ['neotest-haskell'] = {},
      ['neotest-deno'] = {},
      ['neotest-java'] = {},
      ['neotest-kotlin'] = {},
      ['neotest-foundry'] = {},
      ['neotest-zig'] = {},
      ['neotest-gtest'] = {},
      ['neotest-gradle'] = {},
      ['neotest-bazel'] = {},
      ['neotest-bash'] = {},
      ['neotest-hardhat'] = {},
      ['neotest-swift-testing'] = {},
    },
  },
}
